version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq
      - echo "Logging in to Docker Hub..."
      - aws secretsmanager get-secret-value --secret-id dockerhub-auth --region us-west-2 --query 'SecretString' --output text | jq -r '.password' | docker login --username $(aws secretsmanager get-secret-value --secret-id dockerhub-auth --region us-west-2 --query 'SecretString' --output text | jq -r '.username') --password-stdin
  pre_build:
    commands:
      - echo "Preparing to build Docker image..."
  build:
    commands:
      - echo "Building Docker image..."
      - docker-compose up --build -d
  post_build:
    commands:
      - echo "Build complete."

artifacts:
  files:
    - '**/*'

eb_codebuild_settings:
  Timeout: 60
  CodeBuildServiceRole: "arn:aws:iam::370052297002:role/codebuild-service-role"
  Image: "aws/codebuild/standard:4.0" # 改成包含 yum 的镜像
  ComputeType: "BUILD_GENERAL1_SMALL"
  artifacts:
    files: '**/*'
