version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq
  pre_build:
    commands:
      - echo "Retrieving DockerHub credentials from Secrets Manager..."
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub-auth --region us-east-1 --query 'SecretString' --output text | jq -r '.username')
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub-auth --region us-east-1 --query 'SecretString' --output text | jq -r '.password')
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo "Building Docker image..."
      - docker-compose up --build -d
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
