version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y jq
  pre_build:
    commands:
      - echo "Preparing to build Docker image..."
  build:
    commands:
      - echo "Building Docker image..."
      - docker-compose up --build -d
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
