services:
  node-api:
    build:
      context: . # 当前目录，确保包含 index.js
      dockerfile: services/node-api/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - my_network

networks:
  my_network:
