version: '3.8'
services:
  node-api:
    build: 
      context: .  # 当前目录，确保包含index.js
      dockerfile: services/node-api/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - kafka
      - mongodb
      - mysql
    environment:
      REDIS_HOST: redis
      KAFKA_HOST: kafka:9092
      MONGO_HOST: mongodb
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ImPassword123@
      MYSQL_DATABASE: node_groundz

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
     
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ImPassword123@
      MYSQL_DATABASE: node_groundz
